### ISSUE TITLE
multiple read_cmd_triggers (as list)?

### ISSUE THREAD

**Issue by onkelandy** [Morg42/MultiDevice#12]
Sort of a special case (of course ;))...
When adding multiple command "sections" in the same hierarchy, e.g. tuner and general from denon, the read command/item gets overwritten and therefore doesn't trigger all read_cmds as expected.

Solution part 1:
put md_read_group_trigger values in a list when creating the struct. So when merging the structs by shng, the list gets merged (this works out of the box)

Solution part 2:
adjust the relevant parts in init.py make list out of single values and iterate through list

**Comment by Morg42** [comment]
The separate sections in the structs are not meant to be "joined" in a single item. The collision of read trigger items described here can - and probably will - also occur with regular command items, either suppressing items or mangling them.

The recommended way is using model-specific structs (if available), the ALL struct, or if explicitly requested, the section structs each in their own respective item.

The ALL struct is not problematic, as all non-existent (or not supported) command can automatically be removed on import.
