### ISSUE TITLE
Merging of lookups not working?

### ISSUE THREAD

**Issue by onkelandy** [Morg42/MultiDevice#13]
For sending as well receiving merging lookup tables doesn't seem to work.
Example device denon has an ALL and MODEL specific lookup for "input". Obviously only the model specific one is taken into account..
```
Feb 13 00:46:54 CET WARNING  plugins.multidevice.denon CP Server Thread-14 command zone1.control.input with value MPLAY produced error on converting value, aborting. Error was: Lookup of value mplay in table INPUT with entries {'phono': 'PHONO', 'cd': 'CD', 'aux2': 'AUX2'} failed, entry not found.  --  (MD_Device.py:send_command:260)
```
(log output modified to see content of lookup dict)

**Comment by Morg42** [comment]
Yep, my fault.

dict.update(dict2) only updates level 1 keys, so existing keys are replaced, which removed the ALL keys and replaced them with model-specific keys.

Fixed via (existing) recursive update function.
