### ISSUE TITLE
Structs den Commands/Models anpassen

### ISSUE THREAD

**Issue by onkelandy** [Morg42/MultiDevice#2]
Variante 1:
Items mit Verweis auf nicht geladenen Command werden automatisch nicht ins Struct aufgenommen. Unteritems auch nicht.

Variante 2:
Items mit Verweis auf nicht geladenen Command werden nicht ins Struct aufgenommen, sofern es keine Unteritems gibt. Ansonsten werden sie ihren md_Einträgen beraubt und das nächste Hierarchielevel wird wieder gleich behandelt

Variante 3:
Definition, welche Structs für welches Model geladen werden sollen

Variante 4:
md_models Attribut, mit dem per Liste pro Item definiert werden kann, bei welchen Modellen das Item geladen werden soll. Sollte ein Unteritem einen vorhandenen Command haben, müsste wie in Variante 2 vorgegangen werden.

Andere Varianten?

**Comment by Morg42** [comment]
Done
