### ISSUE TITLE
Für reply Pattern lookup und valid_list bereitstellen

### ISSUE THREAD

**Issue by onkelandy** [Morg42/MultiDevice#3]
Low prio, aber vielleicht eine Idee..

Wenn ein Lookup für einen command angegeben ist, könnte es hilfreich sein, die dort enthaltenen Keys für den reply-token zu nutzen.
Beispiel, aktueller Denon Command Input für Zone 2 und 3. Dieser muss ganz nach unten in der Liste, damit nicht andere Replies, die mit dem gleichen String anfangen, falsch abgefangen werden (zB Z2PSBAS (\d{2}, Z2SLP(\d{3}|OFF), Z2(\d{2,3})).
```
'reply_token': 'REGEX', 'reply_pattern': 'Z2(.*)', 'lookup': 'INPUT'
```
Wenn das hier ginge..
```
'reply_token': 'REGEX', 'reply_pattern': 'Z2(MD_LOOKUP)', 'lookup': 'INPUT'
```
..und das so aufgelöst würde

```

'reply_pattern': 'Z2(<lookup1>|<lookup2>|<lookup3>)'
```
Ähnlich vielleicht auch valid_list oder valid_list_ci Angaben. 

Aktuelle Lösung ist entweder eine sehr gefinkelte Regex oder das Hinunterschieben des commands an das Ende der Liste. Also kein Drama.

**Comment by Morg42** [comment]
done

**Comment by onkelandy** [comment]
Nice. Wär noch ein MD_VALID(_CI) denkbar, falls man ne valid_list am Start hat?

**Comment by Morg42** [comment]
done
