### ISSUE TITLE
Minor issue: read_group trigger attributes get deleted when respective item is created additionally

### ISSUE THREAD

**Issue by onkelandy** [Morg42/MultiDevice#4]
Nothing too important as it can be fixed by adding the relevant attributes manually. However..
```
'item_attrs': {'item_template': 'time', 'enforce': True, 'read_groups': [{'name': 'player.control.time_poll', 'trigger': 'poll'}]}
item_templates = {
    'time': {
        'poll':
            {
                'type': 'bool',
                'eval': 'True if sh....playmode() == "play" else None',
                'enforce_updates': True,
                'cycle': '5 = True',
                #'md_device': 'DEVICENAME', -> needs to be added manually
                #'md_read_group_trigger': 'player.control.time_poll' -> needs to be added manually
            }
    }

}
```
leads to missing read_group_trigger attributes for the "poll" item that is declared as the read_group trigger.

**Comment by Morg42** [comment]
templates are exactly that - templates. As these are not items created and "controlled" by the struct generator, there can be no intelligent supplement of item attributes. The generator can not know if this is necessary or not. 
So, please add the missing attributes to the template.
